### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by zeroandexe** [OptimalScale/LMFlow#229]
在windows的wsl2上搭建的环境，运行聊天程序都是ok的。
但是在尝试运行`./scripts/run_finetune.sh` 失败了，将 block_size 设置为 1 也是相同的错误。
不知道是不是lmflow与deepspeeds的库兼容的问题。
```
GPU memory:  12G        //3060
RAM memory:  48G
```
```
(lmflow) [root@a4113ca43b08 LMFlow-main]# ./scripts/run_finetune.sh 
[2023-04-14 18:11:42,924] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-04-14 18:11:42,939] [INFO] [runner.py:550:main] cmd = /home/minicoda3/envs/lmflow/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=11000 --enable_each_rank_log=None examples/finetune.py --model_name_or_path gpt2 --dataset_path /root/code/LMFlow-main/data/alpaca/train --output_dir /root/code/LMFlow-main/output_models/finetune --overwrite_output_dir --num_train_epochs 0.01 --learning_rate 2e-5 --block_size 1 --per_device_train_batch_size 1 --deepspeed configs/ds_config_zero3.json --bf16 --run_name finetune --validation_split_percentage 0 --logging_steps 20 --do_train --ddp_timeout 72000 --save_steps 5000 --dataloader_num_workers 1
[2023-04-14 18:11:44,145] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0]}
[2023-04-14 18:11:44,145] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-04-14 18:11:44,145] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-04-14 18:11:44,145] [INFO] [launch.py:162:main] dist_world_size=1
[2023-04-14 18:11:44,145] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0
[2023-04-14 18:11:46,151] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
04/14/2023 18:11:46 - WARNING - lmflow.pipeline.finetuner - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False
04/14/2023 18:11:47 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-0f19a1f3dd71ee72/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
[2023-04-14 18:11:51,059] [INFO] [partition_parameters.py:415:__exit__] finished initializing model with 0.16B parameters
/home/minicoda3/envs/lmflow/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py:2547: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
04/14/2023 18:11:52 - WARNING - datasets.fingerprint - Parameter 'function'=<function HFDecoderModel.tokenize.<locals>.tokenize_function at 0x7f2d4739c820> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
04/14/2023 18:11:52 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-0f19a1f3dd71ee72/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-1c80317fa3b1799d.arrow
04/14/2023 18:11:52 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-0f19a1f3dd71ee72/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-dc75677609001201.arrow
Using /root/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py39_cu117/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module cpu_adam...
Time to load cpu_adam op: 0.3251173496246338 seconds
Using /root/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
Emitting ninja build file /root/.cache/torch_extensions/py39_cu117/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.1777784824371338 seconds
Parameter Offload: Total persistent parameters: 121344 in 98 params
Traceback (most recent call last):
  File "/root/code/LMFlow-main/examples/finetune.py", line 70, in <module>
    main()
  File "/root/code/LMFlow-main/examples/finetune.py", line 66, in main
    tuned_model = finetuner.tune(model=model, lm_dataset=lm_dataset)
  File "/root/code/LMFlow-main/src/lmflow/pipeline/finetuner.py", line 232, in tune
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/minicoda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/home/minicoda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 1731, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/home/minicoda3/envs/lmflow/lib/python3.9/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/minicoda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/minicoda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 340, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/minicoda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1298, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/minicoda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1599, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/home/minicoda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 169, in __init__
    self.__inf_or_nan_tracker: Tensor = torch.zeros(
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2023-04-14 18:11:56,161] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 1123
[2023-04-14 18:11:56,162] [ERROR] [launch.py:324:sigkill_handler] ['/home/minicoda3/envs/lmflow/bin/python', '-u', 'examples/finetune.py', '--local_rank=0', '--model_name_or_path', 'gpt2', '--dataset_path', '/root/code/LMFlow-main/data/alpaca/train', '--output_dir', '/root/code/LMFlow-main/output_models/finetune', '--overwrite_output_dir', '--num_train_epochs', '0.01', '--learning_rate', '2e-5', '--block_size', '1', '--per_device_train_batch_size', '1', '--deepspeed', 'configs/ds_config_zero3.json', '--bf16', '--run_name', 'finetune', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--save_steps', '5000', '--dataloader_num_workers', '1'] exits with return code = 1
```
```
(lmflow) [root@a4113ca43b08 LMFlow-main]# pip3 list 
Package                  Version    Editable project location
------------------------ ---------- --------------------------
accelerate               0.18.0
aiohttp                  3.8.4
aiosignal                1.3.1
appdirs                  1.4.4
async-timeout            4.0.2
attrs                    22.2.0
certifi                  2022.12.7
charset-normalizer       3.1.0
click                    8.1.3
cmake                    3.26.3
datasets                 2.10.1
deepspeed                0.8.3
dill                     0.3.6
docker-pycreds           0.4.0
filelock                 3.11.0
Flask                    2.2.3
Flask-Cors               3.0.10
frozenlist               1.3.3
fsspec                   2023.4.0
gitdb                    4.0.10
GitPython                3.1.31
hjson                    3.1.0
huggingface-hub          0.13.4
idna                     3.4
importlib-metadata       6.3.0
itsdangerous             2.1.2
Jinja2                   3.1.2
lit                      16.0.1
lmflow                   0.0.1      /root/code/LMFlow-main/src
MarkupSafe               2.1.2
mpi4py                   3.1.4
mpmath                   1.3.0
multidict                6.0.4
multiprocess             0.70.14
networkx                 3.1
ninja                    1.11.1
numpy                    1.24.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
packaging                23.1
pandas                   2.0.0
pathtools                0.1.2
peft                     0.2.0
pip                      23.0.1
protobuf                 4.22.3
psutil                   5.9.4
py-cpuinfo               9.0.0
pyarrow                  11.0.0
pydantic                 1.10.7
python-dateutil          2.8.2
pytz                     2023.3
PyYAML                   6.0
regex                    2023.3.23
requests                 2.28.2
responses                0.18.0
sentencepiece            0.1.98
sentry-sdk               1.19.1
setproctitle             1.3.2
setuptools               65.6.3
six                      1.16.0
smmap                    5.0.0
sympy                    1.11.1
tokenizers               0.13.3
torch                    2.0.0
tqdm                     4.65.0
transformers             4.28.0
triton                   2.0.0
trl                      0.4.1
typing_extensions        4.5.0
tzdata                   2023.3
urllib3                  1.26.15
wandb                    0.14.0
Werkzeug                 2.2.3
wheel                    0.38.4
xxhash                   3.2.0
yarl                     1.8.2
zipp                     3.15.0
```

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! It appears that is a problem related to deepspeed. According to our experience, deepspeed is not fully supported in Windows platform. You may try to replace `deepspeed ${deepspeed_args}` with `python` in `./scripts/run_finetune.sh` to see if it works. Also, you may switch from `ds_config_zero3.json` to `ds_config_zero2.json`, which consumes less CPU memory.

We will add more acceleration backend in the future to solve this problem. Thanks for your understanding 🙏

**Comment by zeroandexe** [comment]
谢谢，这个问题刚刚解决了，是我的环境问题。
通过```ds_report```可以看到：
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/minicoda3/envs/lmflow/lib/python3.9/site-packages/torch']
torch version .................... 2.0.0+cu117
deepspeed install path ........... ['/home/minicoda3/envs/lmflow/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.8.3, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.7
deepspeed wheel compiled w. ...... torch 0.0, cuda 0.0
```
triton与我当前的deepspeed不匹配，采用 ```torch-1.0.0```替换掉```torch-2.0.0```就可以了。
希望对其他人也有帮助。

**Comment by LucasPKU** [comment]
你好，我也遇到了同样的问题，请问你具体是怎么解决的？

**Comment by shizhediao** [comment]
可以试一下升级torch，检查一下torch的版本是否为`2.0.0`

**Comment by LucasPKU** [comment]
> 

torch版本为2.0.0，Triton版本也是2.0.0，ds_report和层主基本一样，能运行run_finetune_with_lora但是运行run_finetune就报错

**Comment by shizhediao** [comment]
我看上面的解决方案是用低版本的torch替换2.0.0  可以试一下
