### ISSUE TITLE
It toke too much time in "Initializing TorchBackend in DeepSpeed with backend nccl " this step!

### ISSUE THREAD

**Issue by devinzhang91** [OptimalScale/LMFlow#406]
I work it in docker contrainer,  CMD:  docker run --gpus all --shm-size=512g xxxx
pip list :
nvidia-nccl-cu11         2.14.3
torch                    2.0.0
When I start to run:  ``` ./scripts/run_finetune.sh ```  or ``` run_evaluation_with_lora.sh ```
It will stuck  "**Initializing TorchBackend in DeepSpeed with backend nccl** "  this step for almost 10 minutes. 
But it can runs normally after this.
My HPC is 8*A100 SXM.

I try with my PC which only have 1* GTX1080 , it run normally, no stuck.

Are there any missing parameters when I starting the container?

**Comment by SHUMKASHUN** [comment]
Hi,
      If you are trying to finetune a relative large model (33B, 65B), it do take some time to initialize and load. You may first try 2*A100 which should take within 5 minutes to see if it works on your machine. Then you can try 8 * A100 and wait for longer time.

**Comment by devinzhang91** [comment]
> Hi, If you are trying to finetune a relative large model (33B, 65B), it do take some time to initialize and load. You may first try 2*A100 which should take within 5 minutes to see if it works on your machine. Then you can try 8 * A100 and wait for longer time.

Thx for reply, I have solved the problem, as long as the environment is connected, it will be normal. Previously, my environment was not connected.
