### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by AlexJJJChen** [OptimalScale/LMFlow#84]
Traceback (most recent call last):
  File "/home/jianc/LMFlow/examples/finetune.py", line 70, in <module>
    main()
  File "/home/jianc/LMFlow/examples/finetune.py", line 66, in main
    tuned_model = finetuner.tune(model=model, lm_dataset=lm_dataset)
  File "/home/jianc/LMFlow/src/lmflow/pipeline/finetuner.py", line 232, in tune
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 1639, in train
    return inner_training_loop(
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 1906, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 2652, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 2684, in compute_loss
    outputs = model(**inputs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/peft/peft_model.py", line 529, in forward
    return self.base_model(
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/opt/modeling_opt.py", line 936, in forward
    outputs = self.model.decoder(
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/opt/modeling_opt.py", line 642, in forward
    pos_embeds = self.embed_positions(attention_mask, past_key_values_length)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    result = hook(self, args)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 348, in _pre_forward_module_hook
    self.pre_sub_module_forward_function(module)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 478, in pre_sub_module_forward_function
    param_coordinator.fetch_sub_module(sub_module)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 349, in fetch_sub_module
    self.__all_gather_params(params_to_prefetch)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 399, in __all_gather_params
    handle = partitioned_params[0].all_gather_coalesced(partitioned_params)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/jianc/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 849, in all_gather_coalesced
    param.ds_tensor.to(get_accelerator().current_device_name()),

**RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.**

**Comment by Jerry00917** [comment]
m -rf ~/.cache/huggingface/datasets

**Comment by research4pan** [comment]
Thanks for your attention! We have received several similar issues recently. The problem was caused by huggingface cache mismatch problem with updated python package dependencies (cache with old `transformers` version doesn't match newer `transformers` versions). The `rm -rf ~/.cache/huggingface/datasets` command should solve the problem.

If you have any further issues, please feel free to reopen the issue. Thanks 😄
